const items = [
    // الحيوانات
    { emoji: "🐶", text: "You got a cute dog that resembles your loyalty!" },
    { emoji: "🐱", text: "You got a charming cat that brings joy!" },
    { emoji: "🐭", text: "You got a tiny mouse, small but clever!" },
    { emoji: "🐹", text: "You got an adorable hamster full of energy!" },
    { emoji: "🐰", text: "You got a lovely rabbit, as soft as a dream!" },
    { emoji: "🦊", text: "You got a clever fox, always one step ahead!" },
    { emoji: "🐻", text: "You got a cuddly bear, strong and protective!" },
    { emoji: "🐼", text: "You got a panda, a symbol of peace and cuteness!" },
    { emoji: "🐻‍❄️", text: "You got a polar bear, as cool as the Arctic!" },
    { emoji: "🐨", text: "You got a koala, calm and lovable!" },
    { emoji: "🐯", text: "You got a tiger, fierce and brave!" },
    { emoji: "🦁", text: "You got a lion, the king of the jungle!" },
    { emoji: "🐮", text: "You got a cow, a provider of nourishment!" },
    { emoji: "🐷", text: "You got a pig, a sign of fortune and abundance!" },
    { emoji: "🐸", text: "You got a frog, ready to leap to success!" },
    { emoji: "🐵", text: "You got a monkey, playful and curious!" },
    { emoji: "🐔", text: "You got a chicken, bringing fresh beginnings!" },
    { emoji: "🐧", text: "You got a penguin, cool and unique!" },
    { emoji: "🐦", text: "You got a bird, spreading freedom and joy!" },
    { emoji: "🐤", text: "You got a chick, full of youthful energy!" },
    { emoji: "🐣", text: "You got a hatching chick, a symbol of new life!" },
    { emoji: "🦆", text: "You got a duck, calm on the surface but focused!" },
    { emoji: "🦅", text: "You got an eagle, soaring high above challenges!" },
    { emoji: "🦉", text: "You got an owl, wise and insightful!" },
    { emoji: "🦇", text: "You got a bat, mysterious yet fascinating!" },
    { emoji: "🐺", text: "You got a wolf, loyal and strong in spirit!" },
    { emoji: "🐗", text: "You got a wild boar, unstoppable and bold!" },
    { emoji: "🐴", text: "You got a horse, fast and determined!" },
    { emoji: "🦄", text: "You got a unicorn, magical and full of wonder!" },
    // الملابس
    { emoji: "👚", text: "You got a blouse, stylish and elegant!" },
    { emoji: "👕", text: "You got a T-shirt, casual and comfortable!" },
    { emoji: "👖", text: "You got jeans, durable and reliable!" },
    { emoji: "👔", text: "You got a tie, professional and sharp!" },
    { emoji: "👗", text: "You got a dress, graceful and classy!" },
    { emoji: "👙", text: "You got a bikini, perfect for sunny beaches!" },
    { emoji: "👘", text: "You got a kimono, cultural and beautiful!" },
    { emoji: "👠", text: "You got a high heel, fashionable and bold!" },
    { emoji: "👡", text: "You got sandals, cool and breezy!" },
    { emoji: "👢", text: "You got boots, tough and adventurous!" },
    { emoji: "👞", text: "You got shoes, reliable for every journey!" },
    { emoji: "👟", text: "You got sneakers, sporty and active!" },
    { emoji: "🎩", text: "You got a top hat, classic and elegant!" },
    { emoji: "🧢", text: "You got a cap, casual and trendy!" },
    { emoji: "🪖", text: "You got a helmet, protective and secure!" },
    { emoji: "⛑️", text: "You got a safety helmet, ready for challenges!" },
    { emoji: "👒", text: "You got a sunhat, perfect for sunny days!" },
    { emoji: "🥽", text: "You got goggles, ready for action!" },
    { emoji: "🥼", text: "You got a lab coat, scientific and smart!" },
    { emoji: "🦺", text: "You got a vest, ready for the outdoors!" },
    // الفواكه
    { emoji: "🍎", text: "You got an apple, fresh and healthy!" },
    { emoji: "🍊", text: "You got an orange, juicy and refreshing!" },
    { emoji: "🍌", text: "You got a banana, sweet and energizing!" },
    { emoji: "🍉", text: "You got a watermelon, perfect for summer!" },
    { emoji: "🍇", text: "You got grapes, tiny bursts of sweetness!" },
    { emoji: "🍓", text: "You got strawberries, red and delightful!" },
    { emoji: "🍒", text: "You got cherries, small but irresistible!" },
    { emoji: "🍍", text: "You got a pineapple, tropical and delicious!" },
    { emoji: "🥭", text: "You got a mango, sweet and exotic!" },
    { emoji: "🥝", text: "You got a kiwi, unique and zesty!" },
    { emoji: "🍅", text: "You got a tomato, versatile and flavorful!" },
    { emoji: "🥥", text: "You got a coconut, refreshing and tropical!" },
    { emoji: "🥑", text: "You got an avocado, creamy and nutritious!" },
    { emoji: "🍆", text: "You got an eggplant, versatile and tasty!" },
    { emoji: "🥔", text: "You got a potato, simple yet satisfying!" },
    { emoji: "🥕", text: "You got a carrot, crunchy and sweet!" },
    { emoji: "🌽", text: "You got corn, golden and delicious!" },
    { emoji: "🌶️", text: "You got a chili pepper, spicy and exciting!" },
    { emoji: "🥒", text: "You got a cucumber, fresh and hydrating!" },
    { emoji: "🥬", text: "You got lettuce, crisp and light!" },
    { emoji: "🧠", text: "You got a brain, symbolizing intelligence and creativity!" },
    { emoji: "💪", text: "You got strength, a sign of power and resilience!" },
    { emoji: "❤️", text: "You got a heart, showing love and compassion!" },
    { emoji: "🦸‍♂️", text: "You got a superhero, representing bravery and leadership!" },
    { emoji: "🦸‍♀️", text: "You got a heroine, symbolizing courage and empowerment!" },
    { emoji: "🦄", text: "You got a unicorn, representing uniqueness and imagination!" },
    { emoji: "🌟", text: "You got a star, shining bright with talent and charisma!" },
    { emoji: "🔥", text: "You got fire, full of passion and energy!" },
    { emoji: "🎨", text: "You got a palette, representing artistic creativity!" },
    { emoji: "📚", text: "You got books, symbolizing wisdom and knowledge!" },
    { emoji: "🌈", text: "You got a rainbow, bringing positivity and hope!" },
    { emoji: "⚡", text: "You got lightning, symbolizing energy and speed!" },
    { emoji: "💎", text: "You got a diamond, symbolizing value and strength!" },
    { emoji: "🚀", text: "You got a rocket, representing ambition and progress!" },
    { emoji: "🌍", text: "You got Earth, showing global awareness and unity!" },
  ];
  
  module.exports = items;
  